import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Cat(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("cat.glb");

  useFrame(() => {
    group.current.rotation.y += 0.004
  });

  return (
    <group ref={group} position={[0, 0, -2.1]} {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.material_51}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.material_52}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.material_51}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.material_50}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.material_49}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.material_48}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.material_47}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.material_46}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.material_45}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.material_44}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.material_43}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.material_42}
          />
          <mesh
            geometry={nodes.Object_27.geometry}
            material={materials.material_41}
          />
          <mesh
            geometry={nodes.Object_29.geometry}
            material={materials.material_40}
          />
          <mesh
            geometry={nodes.Object_31.geometry}
            material={materials.material_39}
          />
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.material_38}
          />
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials.material_37}
          />
          <mesh
            geometry={nodes.Object_37.geometry}
            material={materials.material_36}
          />
          <mesh
            geometry={nodes.Object_39.geometry}
            material={materials.material_35}
          />
          <mesh
            geometry={nodes.Object_41.geometry}
            material={materials.material_34}
          />
          <mesh
            geometry={nodes.Object_43.geometry}
            material={materials.material_32}
          />
          <mesh
            geometry={nodes.Object_45.geometry}
            material={materials.material_31}
          />
          <mesh
            geometry={nodes.Object_47.geometry}
            material={materials.material_30}
          />
          <mesh
            geometry={nodes.Object_49.geometry}
            material={materials.material_29}
          />
          <mesh
            geometry={nodes.Object_51.geometry}
            material={materials.material_28}
          />
          <mesh
            geometry={nodes.Object_53.geometry}
            material={materials.material_27}
          />
          <mesh
            geometry={nodes.Object_55.geometry}
            material={materials.material_26}
          />
          <mesh
            geometry={nodes.Object_57.geometry}
            material={materials.material_25}
          />
          <mesh
            geometry={nodes.Object_59.geometry}
            material={materials.material_24}
          />
          <mesh
            geometry={nodes.Object_61.geometry}
            material={materials.material_23}
          />
          <mesh
            geometry={nodes.Object_63.geometry}
            material={materials.material_22}
          />
          <mesh
            geometry={nodes.Object_65.geometry}
            material={materials.material_21}
          />
          <mesh
            geometry={nodes.Object_67.geometry}
            material={materials.material_20}
          />
          <mesh
            geometry={nodes.Object_69.geometry}
            material={materials.material_19}
          />
          <mesh
            geometry={nodes.Object_71.geometry}
            material={materials.material_18}
          />
          <mesh
            geometry={nodes.Object_73.geometry}
            material={materials.material_17}
          />
          <mesh
            geometry={nodes.Object_75.geometry}
            material={materials.material_33}
          />
          <mesh
            geometry={nodes.Object_77.geometry}
            material={materials.material_16}
          />
          <mesh
            geometry={nodes.Object_79.geometry}
            material={materials.material_15}
          />
          <mesh
            geometry={nodes.Object_81.geometry}
            material={materials.material_14}
          />
          <mesh
            geometry={nodes.Object_83.geometry}
            material={materials.material_13}
          />
          <mesh
            geometry={nodes.Object_85.geometry}
            material={materials.material_12}
          />
          <mesh
            geometry={nodes.Object_87.geometry}
            material={materials.material_11}
          />
          <mesh
            geometry={nodes.Object_89.geometry}
            material={materials.material_10}
          />
          <mesh
            geometry={nodes.Object_91.geometry}
            material={materials.material_9}
          />
          <mesh
            geometry={nodes.Object_93.geometry}
            material={materials.material_8}
          />
          <mesh
            geometry={nodes.Object_95.geometry}
            material={materials.material_7}
          />
          <mesh
            geometry={nodes.Object_97.geometry}
            material={materials.material_6}
          />
          <mesh
            geometry={nodes.Object_99.geometry}
            material={materials.material_5}
          />
          <mesh
            geometry={nodes.Object_101.geometry}
            material={materials.material_4}
          />
          <mesh
            geometry={nodes.Object_103.geometry}
            material={materials.material_3}
          />
          <mesh
            geometry={nodes.Object_105.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_107.geometry}
            material={materials.material_1}
          />
          <mesh
            geometry={nodes.Object_109.geometry}
            material={materials.material_0}
          />
        </group>
      </group>
    </group >
  );
}

useGLTF.preload("/cat.glb");
